insert into movie (title, genre, age_limit, duration, release_year, country, description, image_name) values ('Skazani na Shawshank', 'DRAMA', 'MIN_15', 142, 1994, 'USA', 'Film nakręcony na podstawie książki mistrza horrorów Stephena Kinga. Andy Dufresne (Tim Robbins), dobrze zarabiający bankier z Nowej Anglii, zostaje oskarżony o podwójne zabójstwo - swojej żony i jej kochanka. Uparcie twierdzi, że jest niewinny, ale dzięki niezbitym dowodom zostaje skazany na podwójne dożywocie w więzieniu Shawshank. Shawshank rządzi hipokryta i fanatyk biblijny, naczelnik Norton (Bob Gunton), a wraz z nim sadystyczni strażnicy. Andy już po kilku dniach poznaje brutalną, więzienną rzeczywistość, ale dzięki wrodzonej inteligencji, sprytowi oraz pomocy przyjaciela Ellisa Boyda "Reda" Reddinga (Morgan Freeman) udaje mu się zachować nadzieję, która pozwoli dokonać zemsty.', 'skazani_na_shawshank.jpg');
insert into movie (title, genre, age_limit, duration, release_year, country, description, image_name) values ('Zielona mila', 'DRAMA', 'MIN_15', 188, 1999, 'USA', 'Rok 1935. Paul Edgecombe (Tom Hanks) jest jednym ze strażników bloku śmierci w więzieniu Cold Mountain. Do jego obowiązków należy odprowadzanie skazańców do celi śmierci długim korytarzem, wyłożonym zieloną wykładziną, zwaną "Zieloną milą". Pewnego dnia do więzienia przybywa olbrzymi czarnoskóry skazaniec, John Coffey (Michael Clarke Duncan). Ma oczekiwać na karę śmierci za zamordowanie dwóch białych dziewczynek. Jego wizyta na zawsze zmieni życie Paula i pozostałych pracowników więzienia.', 'zielona_mila.jpg');
insert into movie (title, genre, age_limit, duration, release_year, country, description, image_name) values ('Pulp Fiction', 'CRIME', 'MIN_18', 154, 1994, 'USA', 'Płatni mordercy, Jules (Samuel L. Jackson) i Vincent (John Travolta), dostają zlecenie, by odzyskać z rąk przypadkowych rabusiów tajemniczą walizkę bossa mafii. Nie dość tego, Vincent dostaje kolejną robotę - na czas nieobecności gangstera w mieście ma zaopiekować się jego poszukującą wrażeń żoną Mią (Uma Thurman). Vincent i Jules niespodziewanie wpadają po uszy, gdy przypadkowo zabijają zakładnika. Kłopoty ma też podupadły bokser (Bruce Willis), który otrzymał dużą sumę za przegranie swojej walki. Walkę jednak wygrywa, a Los Angeles staje się od tej chwili dla niego za małe. Specjaliści od mokrej roboty będą mieli co robić...', 'pulp_fiction.jpg');
insert into movie (title, genre, age_limit, duration, release_year, country, description, image_name) values ('Milczenie owiec', 'THRILLER', 'MIN_15', 118, 1991, 'USA', 'Agentce FBI, Clarise Starling (Jodie Foster), zostaje powierzona sprawa "Buffalo Billa", seryjnego mordercy wyróżniającego się szczególnym okrucieństwem wobec swych ofiar, które odziera ze skóry. Sprawę pomaga jej rozwikłać inny, niezwykle inteligentny i niebezpieczny morderca - Hannibal Lecter (Anthony Hopkins) - pacjent więziennego centrum psychiatrycznego. Hannibal jest zauroczony Clarice, a w zamian za odkrywanie przez nią części swej przeszłości, kawałek po kawałku odkrywa dla niej tajemnicę morderstw.', 'milczenie_owiec.jpg');
insert into movie (title, genre, age_limit, duration, release_year, country, description, image_name) values ('Dwunastu gniewnych ludzi', 'DRAMA', 'MIN_15', 96, 1957, 'USA', 'Dwunastu przysięgłych w procesie o morderstwo rozpatruje kwestię winy. Wszyscy poza jednym są pewni, że oskarżony zamordował swego ojca. Jednak wyrok musi być jednomyślny. Rozpętuje się gorąca dyskusja, w toku której wątpiący przekonuje innych do swego zdania.', 'dwunastu_gniewnych_ludzi.jpg');
insert into movie (title, genre, age_limit, duration, release_year, country, description, image_name) values ('Forrest Gump', 'COMEDY', 'MIN_12', 142, 1994, 'USA', '"Forrest Gump" to romantyczna historia, w której Tom Hanks wcielił się w tytułową postać - nierozgarniętego młodego człowieka o wielkim sercu i zdolności do odnajdywania się w największych wydarzeniach w historii USA, począwszy od swego dzieciństwa w latach 50-tych. Po tym, jak staje się gwiazdą footballu, odznaczonym bohaterem wojennym i odnoszącym sukcesy biznesmenem, główny bohater zyskuje status osobistości, lecz nigdy nie rezygnuje z poszukiwania tego, co dla niego najważniejsze - miłości swej przyjaciółki, Jenny Curran.', 'forrest_gump.jpg');
insert into movie (title, genre, age_limit, duration, release_year, country, description, image_name) values ('Nietykalni', 'BIOGRAPHY', 'MIN_12', 112, 2011, 'FRANCE', 'Ta historia zdarzyła się naprawdę. Sparaliżowany na skutek wypadku milioner zatrudnia do pomocy i opieki młodego chłopaka z przedmieścia, który właśnie wyszedł z więzienia. Zderzenie dwóch skrajnie różnych światów daje początek szeregowi niewiarygodnych przygód i przyjaźni, która czyni ich... nietykalnymi.', 'nietykalni.jpg');
insert into movie (title, genre, age_limit, duration, release_year, country, description, image_name) values ('Pianista', 'BIOGRAPHY', 'MIN_12', 150, 2002, 'POLAND', 'Ekranizacja wspomnień Władysława Szpilmana. W roli głównej Adrien Brody ("Cienka czerwona linia", "Mordercze lato").  Władysław Szpilman, wybitny polski pianista żydowskiego pochodzenia żyje w warszawskim getcie. Dzieli tam okrutny los i upokorzenie swojego narodu. Przed ostateczną "wywózką" mieszkańców getta do obozów zagłady udaje mu się stamtąd uciec. Ukrywa się samotnie w ruinach Warszawy. Niespodziewanie to przyjaźń z niemieckim oficerem pozwoli mu przetrwać najcięższy okres... ', 'pianista.jpg');
insert into movie (title, genre, age_limit, duration, release_year, country, description, image_name) values ('Król Lew', 'ANIMATION', 'B_O', 89, 1994, 'USA', 'Film opowiada o losach Simby, młodego lwa, który - oskarżony o nieumyślne zabójstwo swojego ojca, króla Lwiej Skały - zostaje skazany na wygnanie. Władzę w królestwie obejmuje Skaza, brat zmarłego władcy. Mija kilka lat. Pewnego dnia Simba spotyka dawną przyjaciółkę, od której dowiaduje się, że królestwo chyli się ku upadkowi. Młody następca tronu postanawia powrócić do dawnej ojczyzny i odzyskać zabrany mu podstępem tron.', 'krol_lew.jpg');
insert into movie (title, genre, age_limit, duration, release_year, country, description, image_name) values ('Slumdog. Milioner z ulicy', 'DRAMA', 'MIN_12', 120, 2008, 'GREAT_BRITAIN', 'Jamal, mieszkaniec slumsów Bombaju, w wieku 18 lat bierze udział w hinduskiej wersji "Milionerów". Od finałowej wygranej dzieli go ostatnie pytanie, jednak zanim zdąży na nie odpowiedzieć, aresztuje go policja. Funkcjonariusze chcą się dowiedzieć jak chłopak może wiedzieć tak dużo. Jamal opowiada prawdziwą historię dzieciństwa, przemocy i miłości swojego życia. To ulica była jego szkołą. Szkołą przetrwania...', 'slumdog.jpg');
insert into movie (title, genre, age_limit, duration, release_year, country, description, image_name) values ('Ojciec chrzestny', 'CRIME', 'MIN_18', 175, 1972, 'USA', 'USA, koniec II wojny światowej. Szefem nowojorskiej mafii jest sędziwy Don Vito Corleone (Marlon Brando), a jego pomocnikami są synowie: Sonny (James Caan) i Fredo (John Cazale) oraz inteligentny i rozważny Irlandczyk, Tom Hagen (Robert Duvall). Trzeci syn Vito, Michael (Al Pacino), absolwent wyższej uczelni, jest przeciwny działalności ojca. Pewnego dnia rodzina Corleone, odmawiając udziału w dystrybucji narkotyków, staje się niepotrzebną przeszkodą dla innych mafii. Dochodzi do nieudanego zamachu na Dona Corleone, a następnie do "wielkiej wojny" nowojorskich gangów, w której niespodziewanie odegra kluczową rolę Michael.', 'ojciec_chrzestny.jpg');

insert into auditorium(name, rows, columns) values ('A', 9, 18);
insert into auditorium(name, rows, columns) values ('B', 8, 22);
insert into auditorium(name, rows, columns) values ('C', 8, 18);
insert into auditorium(name, rows, columns) values ('D', 10, 12);
insert into auditorium(name, rows, columns) values ('E', 14, 12);
insert into auditorium(name, rows, columns) values ('F', 10, 8);
insert into auditorium(name, rows, columns) values ('G', 9, 9);
insert into auditorium(name, rows, columns) values ('H', 7, 9);
insert into auditorium(name, rows, columns) values ('I', 8, 11);
insert into auditorium(name, rows, columns) values ('J', 11, 12);

insert into show (movie_id, auditorium_id, show_date, show_time) values (1, 1, CURRENT_DATE, '11:30');
insert into show (movie_id, auditorium_id, show_date, show_time) values (1, 1, CURRENT_DATE, '15:15');
insert into show (movie_id, auditorium_id, show_date, show_time) values (1, 3, CURRENT_DATE, '20:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (1, 4, CURRENT_DATE + integer '1', '12:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (1, 5, CURRENT_DATE + integer '1', '15:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (1, 6, CURRENT_DATE + integer '1', '19:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (1, 1, CURRENT_DATE + integer '1', '22:30');
insert into show (movie_id, auditorium_id, show_date, show_time) values (1, 2, CURRENT_DATE + integer '2', '11:30');
insert into show (movie_id, auditorium_id, show_date, show_time) values (1, 4, CURRENT_DATE + integer '2', '16:30');
insert into show (movie_id, auditorium_id, show_date, show_time) values (1, 8, CURRENT_DATE + integer '2', '21:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (1, 4, CURRENT_DATE + integer '3', '14:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (1, 5, CURRENT_DATE + integer '3', '17:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (1, 6, CURRENT_DATE + integer '3', '21:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (1, 3, CURRENT_DATE + integer '4', '16:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (1, 1, CURRENT_DATE + integer '4', '21:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (1, 5, CURRENT_DATE + integer '5', '18:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (1, 6, CURRENT_DATE + integer '6', '21:15');
insert into show (movie_id, auditorium_id, show_date, show_time) values (2, 8, CURRENT_DATE, '12:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (2, 1, CURRENT_DATE, '17:45');
insert into show (movie_id, auditorium_id, show_date, show_time) values (2, 8, CURRENT_DATE, '21:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (2, 7, CURRENT_DATE + integer '1', '14:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (2, 10, CURRENT_DATE + integer '1', '18:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (2, 3, CURRENT_DATE + integer '1', '21:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (2, 2, CURRENT_DATE + integer '2', '10:30');
insert into show (movie_id, auditorium_id, show_date, show_time) values (2, 1, CURRENT_DATE + integer '2', '14:30');
insert into show (movie_id, auditorium_id, show_date, show_time) values (2, 4, CURRENT_DATE + integer '2', '19:30');
insert into show (movie_id, auditorium_id, show_date, show_time) values (2, 6, CURRENT_DATE + integer '3', '12:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (2, 8, CURRENT_DATE + integer '3', '16:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (2, 7, CURRENT_DATE + integer '3', '18:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (2, 4, CURRENT_DATE + integer '4', '21:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (2, 3, CURRENT_DATE + integer '5', '16:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (2, 2, CURRENT_DATE + integer '5', '21:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (2, 7, CURRENT_DATE + integer '6', '18:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (2, 8, CURRENT_DATE + integer '6', '21:15');
insert into show (movie_id, auditorium_id, show_date, show_time) values (3, 9, CURRENT_DATE, '12:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (3, 10, CURRENT_DATE + integer '1', '13:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (3, 1, CURRENT_DATE + integer '1', '18:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (3, 2, CURRENT_DATE + integer '2', '14:30');
insert into show (movie_id, auditorium_id, show_date, show_time) values (3, 2, CURRENT_DATE + integer '2', '18:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (3, 3, CURRENT_DATE + integer '3', '21:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (3, 5, CURRENT_DATE + integer '4', '10:30');
insert into show (movie_id, auditorium_id, show_date, show_time) values (3, 4, CURRENT_DATE + integer '4', '14:30');
insert into show (movie_id, auditorium_id, show_date, show_time) values (3, 7, CURRENT_DATE + integer '4', '19:30');
insert into show (movie_id, auditorium_id, show_date, show_time) values (3, 8, CURRENT_DATE + integer '5', '12:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (3, 6, CURRENT_DATE + integer '5', '16:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (3, 2, CURRENT_DATE + integer '5', '18:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (3, 3, CURRENT_DATE + integer '6', '16:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (3, 5, CURRENT_DATE + integer '6', '21:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (4, 4, CURRENT_DATE, '12:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (4, 7, CURRENT_DATE + integer '1', '13:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (4, 8, CURRENT_DATE + integer '2', '18:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (4, 9, CURRENT_DATE + integer '3', '14:30');
insert into show (movie_id, auditorium_id, show_date, show_time) values (4, 9, CURRENT_DATE + integer '4', '18:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (4, 3, CURRENT_DATE + integer '5', '21:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (4, 10, CURRENT_DATE + integer '6', '10:30');
insert into show (movie_id, auditorium_id, show_date, show_time) values (5, 2, CURRENT_DATE, '13:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (5, 3, CURRENT_DATE + integer '1', '20:15');
insert into show (movie_id, auditorium_id, show_date, show_time) values (5, 9, CURRENT_DATE + integer '2', '15:30');
insert into show (movie_id, auditorium_id, show_date, show_time) values (5, 5, CURRENT_DATE + integer '2', '18:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (5, 5, CURRENT_DATE + integer '3', '10:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (5, 3, CURRENT_DATE + integer '3', '16:30');
insert into show (movie_id, auditorium_id, show_date, show_time) values (5, 2, CURRENT_DATE + integer '4', '14:30');
insert into show (movie_id, auditorium_id, show_date, show_time) values (5, 1, CURRENT_DATE + integer '4', '18:30');
insert into show (movie_id, auditorium_id, show_date, show_time) values (5, 8, CURRENT_DATE + integer '5', '12:15');
insert into show (movie_id, auditorium_id, show_date, show_time) values (5, 7, CURRENT_DATE + integer '5', '16:15');
insert into show (movie_id, auditorium_id, show_date, show_time) values (5, 5, CURRENT_DATE + integer '5', '18:45');
insert into show (movie_id, auditorium_id, show_date, show_time) values (5, 5, CURRENT_DATE + integer '6', '19:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (6, 7, CURRENT_DATE + integer '2', '15:30');
insert into show (movie_id, auditorium_id, show_date, show_time) values (6, 4, CURRENT_DATE + integer '2', '19:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (6, 3, CURRENT_DATE + integer '3', '12:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (6, 2, CURRENT_DATE + integer '3', '18:30');
insert into show (movie_id, auditorium_id, show_date, show_time) values (6, 7, CURRENT_DATE + integer '4', '14:30');
insert into show (movie_id, auditorium_id, show_date, show_time) values (6, 4, CURRENT_DATE + integer '4', '17:30');
insert into show (movie_id, auditorium_id, show_date, show_time) values (6, 5, CURRENT_DATE + integer '4', '18:15');
insert into show (movie_id, auditorium_id, show_date, show_time) values (6, 8, CURRENT_DATE + integer '5', '16:15');
insert into show (movie_id, auditorium_id, show_date, show_time) values (6, 3, CURRENT_DATE + integer '6', '17:45');
insert into show (movie_id, auditorium_id, show_date, show_time) values (6, 3, CURRENT_DATE + integer '6', '19:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (7, 4, CURRENT_DATE + integer '2', '15:30');
insert into show (movie_id, auditorium_id, show_date, show_time) values (7, 5, CURRENT_DATE + integer '2', '19:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (7, 8, CURRENT_DATE + integer '3', '12:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (7, 8, CURRENT_DATE + integer '3', '14:30');
insert into show (movie_id, auditorium_id, show_date, show_time) values (7, 10, CURRENT_DATE + integer '3', '19:30');
insert into show (movie_id, auditorium_id, show_date, show_time) values (7, 9, CURRENT_DATE + integer '4', '17:30');
insert into show (movie_id, auditorium_id, show_date, show_time) values (8, 9, CURRENT_DATE, '18:15');
insert into show (movie_id, auditorium_id, show_date, show_time) values (8, 2, CURRENT_DATE + integer '2', '16:15');
insert into show (movie_id, auditorium_id, show_date, show_time) values (8, 3, CURRENT_DATE + integer '2', '19:45');
insert into show (movie_id, auditorium_id, show_date, show_time) values (8, 5, CURRENT_DATE + integer '3', '13:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (8, 10, CURRENT_DATE + integer '4', '15:30');
insert into show (movie_id, auditorium_id, show_date, show_time) values (8, 6, CURRENT_DATE + integer '4', '19:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (8, 7, CURRENT_DATE + integer '4', '22:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (8, 8, CURRENT_DATE + integer '5', '14:30');
insert into show (movie_id, auditorium_id, show_date, show_time) values (8, 2, CURRENT_DATE + integer '5', '19:30');
insert into show (movie_id, auditorium_id, show_date, show_time) values (8, 1, CURRENT_DATE + integer '5', '21:20');
insert into show (movie_id, auditorium_id, show_date, show_time) values (9, 3, CURRENT_DATE + integer '1', '18:15');
insert into show (movie_id, auditorium_id, show_date, show_time) values (9, 3, CURRENT_DATE + integer '2', '16:15');
insert into show (movie_id, auditorium_id, show_date, show_time) values (9, 4, CURRENT_DATE + integer '3', '19:45');
insert into show (movie_id, auditorium_id, show_date, show_time) values (9, 5, CURRENT_DATE + integer '4', '13:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (9, 6, CURRENT_DATE + integer '4', '15:30');
insert into show (movie_id, auditorium_id, show_date, show_time) values (9, 5, CURRENT_DATE + integer '4', '19:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (10, 7, CURRENT_DATE, '13:20');
insert into show (movie_id, auditorium_id, show_date, show_time) values (10, 8, CURRENT_DATE + integer '1', '18:40');
insert into show (movie_id, auditorium_id, show_date, show_time) values (10, 7, CURRENT_DATE + integer '2', '19:30');
insert into show (movie_id, auditorium_id, show_date, show_time) values (10, 4, CURRENT_DATE + integer '2', '21:20');
insert into show (movie_id, auditorium_id, show_date, show_time) values (10, 4, CURRENT_DATE + integer '3', '11:15');
insert into show (movie_id, auditorium_id, show_date, show_time) values (10, 5, CURRENT_DATE + integer '3', '16:15');
insert into show (movie_id, auditorium_id, show_date, show_time) values (10, 3, CURRENT_DATE + integer '3', '19:45');
insert into show (movie_id, auditorium_id, show_date, show_time) values (10, 7, CURRENT_DATE + integer '4', '13:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (10, 4, CURRENT_DATE + integer '4', '15:30');
insert into show (movie_id, auditorium_id, show_date, show_time) values (10, 2, CURRENT_DATE + integer '6', '18:00');
insert into show (movie_id, auditorium_id, show_date, show_time) values (10, 8, CURRENT_DATE + integer '6', '21:00');

insert into reservation(show_id, timestamp, first_name, last_name, phone_number) values (1, CURRENT_TIMESTAMP, 'Jan', 'Nowak', '111111111');

insert into reserved_seat(show_id, seat, reservation_id) values (3, 'G1', 1);
insert into reserved_seat(show_id, seat, reservation_id) values (3, 'G2', 1);
insert into reserved_seat(show_id, seat, reservation_id) values (3, 'G3', 1);
insert into reserved_seat(show_id, seat, reservation_id) values (3, 'H8', 1);
insert into reserved_seat(show_id, seat, reservation_id) values (3, 'H9', 1);
insert into reserved_seat(show_id, seat, reservation_id) values (3, 'H10', 1);
insert into reserved_seat(show_id, seat, reservation_id) values (3, 'H11', 1);
insert into reserved_seat(show_id, seat, reservation_id) values (3, 'H12', 1);
insert into reserved_seat(show_id, seat, reservation_id) values (3, 'H13', 1);

insert into ticket_type(category, price) values ('NORMALNY', 21);
insert into ticket_type(category, price) values ('ULGOWY', 14);
insert into ticket_type(category, price) values ('SENIOR', 14);
insert into ticket_type(category, price) values ('STUDENCKI', 16);

insert into event(title, event_date, short_description, description, image_name) values ('Sylwester w Kinomanii', '2018-12-31', 'Kinomania zaprasza wszystkich spragnionych dobrej zabawy na porządną porcję sylwestrowego szaleństwa! W repertuarze premiery i pokazy przedpremierowe produkcji, które rozbawią, wzruszą i przyprawią o dreszczyk emocji.', 'Jest to już kolejny rok z rzędu, kiedy Kinomania organizuje Sylwester Oscarowych Premier Filmowych 2018/19 - jedyna taka filmowo-towarzyska zabawa sylwestrowa w Warszawie.'||E'\n\n'||'Dla uczestników sylwestrowo-filmowego wydarzenia, proponujemy co najmniej trzy pokazy przedpremierowe, które w regularnym repertuarze kin znajdą się dopiero w pierwszych miesiącach Nowego Roku. Oprócz części filmowej, gwarantujemy też inne atrakcje: symboliczną lampkę szampana o północy (toast noworoczny), zabawę w sali tanecznej przy odpowiednio dobranej oprawie muzycznej, część gastronomiczną (ciepłe potrawy oraz zimne przekąski) oraz w trakcie przerw pomiędzy seansami i odliczaniem o północy - konkursy noworoczne, w których nagrodami są prezenty od Sponsorów i Partnerów nocnego wydarzenia.'||E'\n\n'||'Sylwester 2018/19 warto spędzić wśród innych miłośników dobrych filmów w szampańskiej atmosferze.'||E'\n\n\n'||'HARMONOGRAM NOCY SYLWESTROWEJ:'||E'\n\n'||'20:00 rozpoczęcie Sylwestra Oscarowych Premier Filmowych 2018/19, konkursy z nagrodami'||E'\n'||'21:00 WITAJCIE W MARWEN (116'') | sala studyjna'||E'\n'||'23:15 ciepły posiłek | makaron, bigos, kapusta z grzybami'||E'\n'||'23:30 konkursy z nagrodami, dancing'||E'\n'||'00:00 Toast noworoczny'||E'\n'||'00:45 GREEN BOOK (130'') | sala studyjna'||E'\n'||'03:15 ciepły posiłek | krem warzywny, barszcz'||E'\n'||'04:00 ONI (151'') | sala studyjna', 'sylwester.jpg');
insert into event(title, event_date, short_description, description, image_name) values ('Mikołajki dla dzieci i rodziców', '2018-12-06', 'Kinomania zaprasza wszystkich kinomanów na filmowe mikołajki. 6 grudnia 2018 w godzinach popołudniowych nasze kino odwiedzi Święty Mikołaj, który rozda dzieciom słodkie upominki. Prezenty-niespodzianki pojawią się też na wybranych seansach dla najmłodszych. W mikołajkowym repertuarze świąteczno-zimowe animacje.', 'Kinomania zaprasza wszystkich kinomanów na filmowe mikołajki. 6 grudnia 2018 w godzinach popołudniowych nasze kino odwiedzi Święty Mikołaj, który rozda dzieciom słodkie upominki. Prezenty-niespodzianki pojawią się też na wybranych seansach dla najmłodszych. W mikołajkowym repertuarze świąteczno-zimowe animacje.'||E'\n\n'||'Na ekranach Kinomanii: GRINCH - zabawna, pełna ciepła, oszałamiająco sfilmowana historia świąteczna z olbrzymią dawką optymizmu; MIŚKÓW 2-ÓCH W NOWYM JORKU czyli mnóstwo przygód, humoru i dobrej zabawy w towarzystwie znanych i lubianych bohaterów, MISJA YETI – przygodowa animacja dla całej rodziny, w której będzie można usłyszeć głos himalaisty - Adama Bieleckiego oraz DZIADEK DO ORZECHÓW I CZTERY KRÓLESTWA - ponadczasowa opowieść realizowana z ogromnym rozmachem przez Studio Disney. A ponadto w repertuarze: ROBIN HOOD: POCZĄTEK, AJKA, NARODZINY GWIAZDY, MIŁOŚĆ JEST WSZYSTKIM, PLANETA SINGLI 2, CREED 2.', 'mikolajki.jpg');
insert into event(title, event_date, short_description, description, image_name) values ('Noc Reklamożerców', '2018-10-12', 'Zapraszamy do udziału w 37 edycji Nocy Reklamożerców. Na uczestników czeka ponad 250  najlepszych i najgorszych reklam z całego świata.', 'Noc Reklamożerców to unikalna na świecie impreza, spektakl złożony wyłącznie z  reklam. Obok festiwalu w Cannes to największe międzynarodowe święto reklamy. Organizowana jest od prawie 40 lat, w 40 krajach na świecie.  To jedna z najstarszych organizowanych nieprzerwanie imprez na świecie. W tym roku w Polsce odbędzie się po raz 26.'||E'\n\n'||'Co roku w polskiej Nocy Reklamożerców bierze udział kilka tysięcy fanów reklamy i dobrej zabawy. Głównym tematem trzydziestej ósmej  Nocy Reklamożerców jest MAGIA.  Film reklamowy, jak żaden inny, jest mistrzem iluzji, tworzenia magicznego świata i cudownie wykreowanych wspaniałych sytuacji.'||E'\n\n'||'Czaruje, owiewa wrażeniami, opowiada bajki i legendy.  I tej cudownej magiczności doświadczą widzowie tegorocznej edycji.'||E'\n\n'||'Miłosne historie w .... supermarkecie, japońskie sposoby na szczęście, filmy ocenzurowane, reklamy społeczne to tylko kilka komponentów tegorocznego programu.'||E'\n\n'||'Jak co roku  odrestaurowane perły z reklamowego lamusa przypomną nam vintage blaski reklam sprzed pół wieku.'||E'\n\n'||'Czyli czeka nas, jak co roku, szalona noc, pełna niestandardowych pomysłów dla nieszablonowej publiczności!', 'noc_reklamozercow.jpg');
insert into event(title, event_date, short_description, description, image_name) values ('Liga Mistrzów UEFA - Finał', '2018-05-26', 'Zapraszamy wszystkich fanów piłkarskich wrażeń na pełne emocji sportowe spotkania! Niepowtarzalne warunki panujące w sali kinowej sprawią, że oglądanie piłkarskich zmagań stanie się niezwykle realistyczne. Widzowie będą mogli odnieść wrażenie podziwiania meczu wprost ze stadionowych trybun.', 'Transmisje Ligi Mistrzów po raz pierwszy ekranach kin sieci Kinomania. UEFA Champions League w jakości Full High Definition zobaczymy w kinach sieci Kinomania dzięki platformie nc+.'||E'\n\n'||'Zapraszamy wszystkich fanów piłkarskich wrażeń na pełne emocji sportowe spotkania! Niepowtarzalne warunki panujące w sali kinowej sprawią, że oglądanie piłkarskich zmagań stanie się niezwykle realistyczne. Widzowie będą mogli odnieść wrażenie podziwiania meczu wprost ze stadionowych trybun. Liga Mistrzów UEFA to międzynarodowe europejskie klubowe rozgrywki piłkarskie przeznaczone tylko dla najlepszych drużyn zajmujących czołowe miejsca w europejskich ligach krajowych oraz rozgrywane na europejskich stadionach.'||E'\n\n'||'Zaproś przyjaciół i kibicujcie swoim ulubionym drużynom, podziwiając piłkarskie gwiazdy na kinowym ekranie!', 'final.jpg');

insert into application_user(username, password) values ('admin', '$2a$04$Z0Vxx7mMlwCG70eOHazbQeTEvE.mak9d2YZJ.wI4/lhJVRL4nJyc6');
